### ISSUE TITLE
Results as documents

### ISSUE THREAD

**Issue by horaciocome1** [rosariopfernandes/Tocha#14]
Hi, Ros!

Please tell me, is it possible to have a collection named **_tocha_results_** and then inside that collections goes each document that matches the search?
Since there are lot of users and diferent queries and all getting mixed at the same collection, you could use **queryId = true**. So after adding a query to tocha collections all the result documents would be somehow related to that query id. 
In the end it would be like:

```typescript
ref = await db.collection("tocha_searches").add(query)
querySnapshot = await db.collection("tocha_results").where(ref.id, "==", true).get()
```

Let me know what you think of it!

Thanks

**Comment by thatfiredev** [comment]
Hey @horaciocome1 ,

I'm not sure if I fully understand **why** you need a separate collection (maybe I'm confused because ids aren't usually `true`), but what I understood is that you want to be able to filter through the query results (please let me know if I got this wrong).

I'm expecting The Firebase Team to add more sub-collection features to Firestore next week, so I was considering replacing the 'array of results' with a 'sub-collection of results' when this feature gets released. I believe this should fulfill your needs, since a sub-collection would be queried just like a regular collection.

While these features are not released, you can either:
1. Access the array and iterate through it with a `for` or `while` loop checking which elements have the id you're looking for (its extra work, I know, but it's a temporary workaround);
2. Fork the source code and edit it to match your needs. Feel free to send a PR to this repo afterwards. I'll be happy to review it.

**Comment by horaciocome1** [comment]
Thanks.
I was looking forward to have collection features on the results. Moving to a sub-collection works just fine.

**Comment by thatfiredev** [comment]
I'll keep this issue open until that feature is added.

**Comment by horaciocome1** [comment]
Hi, @rosariopfernandes!

I am looking forward to this. Here you have some updates and I am willing to pull request you my self if you do approve.

Since **where**, **orderBy** and **limit**, are not pertinent to the search itself, but rather to the results of the search, we could significantly boost performance if we managed to leave this part to the firestore itself to handle.

Here is how:
 - You see that array results? What if it was a subcollection? We could throw there each of lunr result inside as a single document, plus a field to score. (the id of the document would be the id of the result). The subcollection would be `/tocha_searches/{searchId}/results`.

Here is the code before:
```javascript
// Read all the documents from the collection to be searched
const querySnapshot = await userCollection.get();
var documents = [];
var lunrIndex = lunr(function() {
    if (queryRef) {
        this.ref(queryRef);
    } else {
        this.ref('key');
    }
    for (var i in fields) {
        this.field(fields[i]);
    }
    querySnapshot.forEach(function (docSnapshot) {
        var snapshotData = docSnapshot.data();
        documents[docSnapshot.id] = docSnapshot.data();
        snapshotData.key = docSnapshot.id;
        this.add(snapshotData);
    }, this);
});
const results = lunrIndex.search(query);
results.forEach(function(result) {
    responseResults.push({
        id: result.ref,
        score: result.score,
        data: documents[result.ref]
    })
});
```

Here are newer:
```javascript
// Read all the documents from the collection to be searched
const querySnapshot = await userCollection.get();
var documents = [];
var lunrIndex = lunr(function() {
    if (queryRef) {
        this.ref(queryRef);
    } else {
        this.ref('key');
    }
    querySnapshot.forEach(function (docSnapshot) {
        var snapshotData = docSnapshot.data();
        documents[docSnapshot.id] = docSnapshot.data();
        snapshotData.key = docSnapshot.id;
        this.add(snapshotData);
    }, this);
});
resultsCollection = firestore.collection(tochaCollection)
    .doc(context.params.searchId)
    .collection('results')
promises = []
const results = lunrIndex.search(query);
results.forEach(function(result) {
    data = documents[result.ref];
    data.tochaScore = result.score;
    promise = resultsCollection.doc(result.ref).set(data); // batch writes can be implemented too
    promises.push(promise);
});
await Promise.all(promises);
```

Then filtering is leaved to client same way he would filter any normal collection query.

 - One thing that bugs me is **naming the score field `tochaScore` sounds awkward**, but leaving just `score` is risky due to the base document might already have an field named `score`.
Also, backwards compatibility will be broken.

 - Another downside of this approach is database quota. Numbers can increase fast because there would be way too much document writes.





Waiting on your feedback.

**Comment by horaciocome1** [comment]
Going this way don't seem that great to me anymore.
The client code would really becomes fancier in my point of view, but the downsides are just too deep down. Example: if client is searching against an `users` collection which has _a million users_ then *Tocha* would have to make way too many writes in `results` subcollection. But, with default approach of dealing with a single document and arrays, only 1 write is billed.
I am closing this issue for now. I don't believe Tocha should go this way anymore.

**Comment by thatfiredev** [comment]
@horaciocome1 Sorry for the delay here, I was still thinking about the possible outcomes of your proposal. I'm glad you pointed out the multiple writes situation, I had not thought of that. 

Also, as I understood, your initial problem was that you wanted to limit the number of results shown the user. I'd suggest doing that on the client side. (even though it might be exhausting if there are way too many results.)
